# Generated by Django 3.2.8 on 2022-05-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_auto_20220502_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Сабақ тақырыбы')),
                ('date', models.CharField(max_length=30, verbose_name='Сабақ қосылды')),
                ('teacher', models.CharField(max_length=30, verbose_name='Сабаты қосты')),
            ],
        ),
        migrations.CreateModel(
            name='TaskIsFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Тапсырма тақырыбы')),
                ('body', models.TextField(verbose_name='Тапсырма мәтіні')),
                ('answer', models.CharField(max_length=25, verbose_name='Тапсырма жауабы')),
                ('t_type', models.CharField(choices=[('Кодты аяқта', 'Кодты аяқта'), ('Бос орынды толтыр', 'Бос орынды толтыр')], default='Кодты аяқта', max_length=100, verbose_name='Тапсырма түрі')),
            ],
        ),
        migrations.CreateModel(
            name='TaskIsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Тапсырма тақырыбы')),
                ('body', models.TextField(verbose_name='Тапсырма мәтіні және коды')),
                ('answer_true', models.CharField(max_length=25, verbose_name='Тапсырма жауабы (Дұрыс)')),
                ('answer_false_1', models.CharField(max_length=25, verbose_name='Тапсырма жауабы (Бұрыс)')),
                ('answer_false_2', models.CharField(max_length=25, verbose_name='Тапсырма жауабы (Бұрыс)')),
                ('answer_false_3', models.CharField(max_length=25, verbose_name='Тапсырма жауабы (Бұрыс)')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Пән атауы')),
                ('course', models.ManyToManyField(blank=True, related_name='course_sbj', to='course.Course', verbose_name='Сабақтар')),
                ('teachers', models.ManyToManyField(blank=True, related_name='teacher_sbj', to='members.Customer', verbose_name='Пән мұғалімдері')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='task_f',
            field=models.ManyToManyField(blank=True, related_name='course_task', to='course.TaskIsFill', verbose_name='Тапсырма түрі (Код және бос орын)'),
        ),
        migrations.AddField(
            model_name='course',
            name='task_t',
            field=models.ManyToManyField(blank=True, related_name='course_task', to='course.TaskIsTest', verbose_name='Тапсырма түрі (Тест)'),
        ),
    ]
