# Generated by Django 3.2.8 on 2022-05-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Сабақ', 'verbose_name_plural': 'Сабақтар'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Пән', 'verbose_name_plural': 'Пәндер'},
        ),
        migrations.AlterModelOptions(
            name='taskisfill',
            options={'verbose_name': 'Тапсырма ', 'verbose_name_plural': 'Тапсырмалар (Код және бос орын)'},
        ),
        migrations.AlterModelOptions(
            name='taskistest',
            options={'verbose_name': 'Тапсырма', 'verbose_name_plural': 'Тапсырмалар (Тест)'},
        ),
    ]
