# Generated by Django 3.2.8 on 2022-05-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220506_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='t_type',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default='1', max_length=100, verbose_name='Сыныпты көрсетіңіз'),
        ),
    ]
