# Generated by Django 3.2.8 on 2022-05-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_t_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='t_type',
            new_name='synup',
        ),
    ]
