# Generated by Django 3.2.8 on 2022-05-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20220510_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskistest',
            old_name='answer_false_1',
            new_name='answer_1',
        ),
        migrations.RenameField(
            model_name='taskistest',
            old_name='answer_false_2',
            new_name='answer_2',
        ),
        migrations.RenameField(
            model_name='taskistest',
            old_name='answer_false_3',
            new_name='answer_3',
        ),
        migrations.RenameField(
            model_name='taskistest',
            old_name='answer_false_4',
            new_name='answer_4',
        ),
    ]
