# Generated by Django 3.2.8 on 2022-05-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20220510_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskisfill',
            name='answer',
            field=models.CharField(max_length=100, verbose_name='Тапсырма жауабы'),
        ),
        migrations.AlterField(
            model_name='taskisfill',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Тапсырма тақырыбы'),
        ),
    ]
