# Generated by Django 3.2.8 on 2022-05-16 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_userresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='userresult',
            name='date',
            field=models.CharField(default='Белгісіз', max_length=35, verbose_name='Уақыты'),
        ),
        migrations.AddField(
            model_name='userresult',
            name='feedback',
            field=models.CharField(default='Кері байланыс жоқ', max_length=520, verbose_name='Кері байланыс'),
        ),
    ]
