# Generated by Django 3.2.8 on 2022-05-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20220516_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskIsIdentify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Тапсырма тақырыбы')),
                ('body', models.TextField(verbose_name='Тапсырма мәтіні')),
                ('task_1', models.CharField(max_length=200, verbose_name='Сұрақ')),
                ('task_2', models.CharField(max_length=200, verbose_name='Сұрақ')),
                ('task_3', models.CharField(max_length=200, verbose_name='Сұрақ')),
                ('task_4', models.CharField(max_length=200, verbose_name='Сұрақ')),
                ('answer_1', models.CharField(max_length=200, verbose_name='Жауап')),
                ('answer_2', models.CharField(max_length=200, verbose_name='Жауап')),
                ('answer_3', models.CharField(max_length=200, verbose_name='Жауап')),
                ('answer_4', models.CharField(max_length=200, verbose_name='Жауап')),
            ],
            options={
                'verbose_name': 'Тапсырма',
                'verbose_name_plural': 'Тапсырмалар (Тест)',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='task_i',
            field=models.ManyToManyField(blank=True, related_name='course_task', to='course.TaskIsIdentify', verbose_name='Тапсырма түрі (Сәйкестендір)'),
        ),
    ]
