# Generated by Django 3.2.8 on 2022-05-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20220519_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskisidentify',
            options={'verbose_name': 'Тапсырма', 'verbose_name_plural': 'Тапсырмалар (Сәйкестендір)'},
        ),
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateTimeField(verbose_name='Сабақ уақыты'),
        ),
    ]
