# Generated by Django 3.2.8 on 2022-05-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20220521_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='user_false_answers',
            field=models.TextField(blank=True, default='Қате сұрақтар белгісіз', verbose_name='Қате сұрақтар'),
        ),
    ]
