# Generated by Django 3.2.3 on 2023-08-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20230815_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskisfill',
            options={'verbose_name': 'Тапсырма ', 'verbose_name_plural': 'Тапсырмалар (Бос орынды толтыр)'},
        ),
        migrations.AddField(
            model_name='taskisfill',
            name='t_type',
            field=models.CharField(choices=[('Бос орынды толтыр', 'Бос орынды толтыр'), ('Кодты аяқта', 'Кодты аяқта')], default='Бос орынды толтыр', max_length=100, verbose_name='Тапсырма түрі'),
        ),
    ]
