# Generated by Django 3.2.3 on 2023-08-15 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_subjectlection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectlection',
            name='subject',
        ),
        migrations.AddField(
            model_name='subjectlection',
            name='lesson',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Сабақ'),
        ),
    ]
