# Generated by Django 3.2.8 on 2022-05-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Тақырыбы')),
                ('body', models.TextField(verbose_name='Түсіндірме')),
                ('video_link', models.TextField(verbose_name='Видео (Youtube)')),
            ],
            options={
                'verbose_name': 'Нұсқаулық',
                'verbose_name_plural': 'Нұсқаулықтар',
            },
        ),
    ]
