# Generated by Django 3.2.10 on 2022-05-01 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_day', models.IntegerField(verbose_name='Туылған күні')),
                ('birth_mounth', models.CharField(max_length=10, verbose_name='Туылған айы')),
                ('birth_year', models.IntegerField(verbose_name='Туылған жылы')),
                ('user_class', models.CharField(choices=[('Оқушы', 'Оқушы'), ('Мұғалім', 'Мұғалім')], default='Оқушы', max_length=100, verbose_name='Қолданушы беделі')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
